[build]
rustc-wrapper = ".cargo/bin/sccache"
pipelining = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[profile.dev.package."*"]
# compiling dependencies optimized improves link times on incimplental builds.
opt-level = 3

[profile.release]
#strip = true  # must be false for cargo-bloat to work

# it may help to inline bigger stuff because it can reduce total size
# in ".cargo/config.toml" "-C", "inline-threshold=150", or even larger
lto = true

