
format = """
$all\
${custom.jj}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[directory]
truncation_length = 4
#truncation_symbol = '…/'
truncate_to_repo = false
fish_style_pwd_dir_length = 2
style = "bold blue"
format =':[$path]($style)[$read_only]($read_only_style) '

[hostname]
style = "green"
ssh_symbol = "@"
format = '$ssh_symbol[$hostname]($style)'

[username]
style_user = "green"
format = '[$user]($style)'
show_always = true

[ruby]
symbol = '🔺 '

[python]
style = "green"

[nodejs]
style = "dimmed yellow"
symbol = "njs "

[custom.jj]
command = "prompt"
format = "$output"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true

